# Video: P1 - JPEG & MPEG


Laura Ruiz Soler

NIA: 240445

laura.ruiz17@estudiant.upf.edu

In [63]:
import numpy as np

In [ ]:
# TASK 1
# Create a translator from 3 values in RGB into the 3 YUV values, plus the opposite operation.
# You can choose the 3 values, or open them from a text file, receive it from command line… feel free.
# Put it in a method.

def rgb_to_yuv(r,g,b):
  y = 0.299*r + 0.587*g + 0.114*b
  u = 0.492*(b-y)
  v = 0.877*(r-y)
  return (y,u,v)

def yuv_to_rgb(y,u,v):
  r = y + 1.140*v
  g = y - 0.395*u - 0.581*v
  b = y + 2.032*u
  return (r,g,b)


# TESTING TASK 1
c = [0.2,0.4,0.6]
(y,u,v) = rgb_to_yuv(c[0], c[1], c[2])
print("(Y,U,V) = ",y,u,v)
(r,g,b) = yuv_to_rgb(y,u,v)
print("(R,G,B) = ",r,g,b)

(Y,U,V) =  0.36300000000000004 0.11660399999999997 -0.14295100000000002
(R,G,B) =  0.20003586000000004 0.399995951 0.599939328


In [66]:
# TASK 2
# Use ffmpeg to resize images into lower quality. Use any image you like
# Now, create a method in previous script to automatise this order.

# We install ffmpeg
!apt-get install ffmpeg

def resize_and_reduce_quality(input_image, output_image, width, height, quality):
  ffmpeg_command = f'ffmpeg -i {input_image} -vf "scale={new_width}:{new_height}" -q:v {quality} {output_image}'
  !{ffmpeg_command}


# TESTING TASK 2
input_image = '/content/sea.JPG' # original size: 5472 × 3072
output_image = '/content/task2_im.jpg' #will have
new_width = 547
new_height = 307
quality = 5
resize_and_reduce_quality(input_image, output_image, new_width, new_height, quality)

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 19 not upgraded.
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq -

In [ ]:
# TASK 3
# Create a method called serpentine which should be able to read the bytes of a JPEG file in the serpentine way we saw.
def serpentine(w,h,m):
  output = []
  i=0
  j=0
  output.append(m[j,i])

  while (i!=w-1 and j!=h-1):
    if (j==0):
      if (i+1<w):
        i+=1
      output.append(m[j,i])
      while (i!=0):
        i-=1
        j+=1
        output.append(m[j,i])
    if (i==0):
      if (j+1<h):
        j+=1
      output.append(m[j,i])
      while (j!=0):
        i+=1
        j-=1
        output.append(m[j,i])

  while(i!=w-1 or j!=h-1):
    j+=1
    output.append(m[j,i])
    while(j<h-1):
        i-=1
        j+=1
        output.append(m[j,i])
    i+=1
    output.append(m[j,i])
    if (i==w-1 and j==h-1):
      break;
    while(i<w-1):
      j-=1
      i+=1
      output.append(m[j,i])

  return output


# TESTING TASK 3
# *It only works for square matrices!!

w,h = 3,3 # We set the size of the matrix
m = np.zeros((w,h)) # Create the matrix
a=0
for i in range(0,h): # Generate a matrix with ascendent sorted numbers in order to see at the end more easily the serpentine effect
  for j in range(0,w):
    m[i,j]=a
    a+=1
print("Original matrix: \n", m)
o = serpentine(w,h,m)
print("\nSerpentine reading: \n", o)

Original matrix: 
 [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

Serpentine reading: 
 [0.0, 1.0, 3.0, 6.0, 4.0, 2.0, 5.0, 7.0, 8.0]


In [70]:
# TASK 4
# Use FFMPEG to transform the previous image into b/w. Do the hardest compression you can.
# Add everything into a new method and comment the results

def compress_b_w(input_image, output_image, width, height, quality):
  ffmpeg_command = f'ffmpeg -i {input_image} -vf "format=gray" -q:v 1 {output_image}'
  !{ffmpeg_command}

# TESTING TASK 4
input_image = '/content/task2_im.jpg'
output_image = '/content/task4_im.jpg'

compress_b_w(input_image, output_image, new_width, new_height, quality)

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enab

With the "format=gray" parameter, we transform our image into black and white. Then, with the "video-quality" parameter (q:v) we set the lowest value, which is 1. For the image created on task 2, we set this value to 5, and now we reduced to 1. We can see as a consequence, that the quality of our new image is reduced, having more artifacts, because the information it contains is more compressed, so we cannot see smaller details.

In [ ]:
# TASK 5
# Create a method which applies a run-lenght encoding from a series of bytes given.

def run_len_encoding(input):
  output = []
  matches = 0
  current_byte = input[0]

  for i in input:
    if (i==current_byte):
      matches+=1
    else:
      output.append(current_byte)
      output.append(matches)
      current_byte = i
      matches = 1

  output.append(current_byte)
  output.append(matches)
  return output

# TESTING TASK 5
input_bytes = 'LLAAAURRAA'
encoded_bytes = run_len_encoding(input_bytes)
print(encoded_bytes)

['L', 2, 'A', 3, 'U', 1, 'R', 2, 'A', 2]


In [ ]:
# TASK 6
# Create a class which can convert, can decode (or both) an input using the DCT. Not necessary a
# JPG encoder or decoder. A class only about DCT is OK too

class dct_conversion:

    # general formula (obatined from class' slides, but for general square matrices, of size NxN)
    def dct(input):
      N = np.size(input, axis=0)
      output = np.zeros((N, N))

      for u in range(N):
        for v in range(N):
          sum=0
          if u==0:
            alpha1 = np.sqrt(1/N)
          else:
            alpha1 = np.sqrt(2/N)

          if v==0:
            alpha2 = np.sqrt(1/N)
          else:
            alpha2 = np.sqrt(2/N)

          for x in range(N-1):
            for y in range(N-1):
              sum += input[x,y]*np.cos((np.pi/N)*(x+0.5)*u)*np.cos((np.pi/N)*(y+0.5)*v)

          total = alpha1*alpha2*sum
          output[u,v]=total
      return output

    def encode(self, input_data):
        # Apply DCT encoding to the input data
        return self.dct2(input_data)

    def decode(self, encoded_data):
        # Apply inverse DCT decoding to the encoded data
        return self.idct2(encoded_data)


# TESTING TASK 6
input_data = np.array([
        [255, 128, 128, 255],
        [255, 255, 255, 255],
        [255, 128, 128, 255],
        [255, 128, 128, 255]
    ], dtype=np.float32)

converted_data = dct_conversion.dct(input_data)
print(converted_data)


[[ 446.75        249.88016703  -64.25        103.50375415]
 [ 201.27937112  108.8280573   -34.6925931    45.0780573 ]
 [-191.25        -83.29338901   63.75        -34.50125138]
 [ -13.82894648   45.0780573    82.83144924   18.6719427 ]]
